import {
  ShoppingCart,
  BookOpen,
  CreditCard,
  Settings,
  Target,
  BarChart3,
  Headset,
  DollarSign,
  Store,
  Users,
  Truck,
  Wallet,
  Bell,
  MonitorSmartphone,
  LayoutDashboard,
  type LucideIcon,
} from "lucide-react"

export interface AdminSection {
  id: string
  title: string
  description: string
  href: string
  icon: LucideIcon
  iconBgColor: string
  keywords: string[]
  group: string
}

export const adminSections: AdminSection[] = [
  // Páginas principais
  {
    id: "dashboard",
    title: "Dashboard",
    description: "Painel principal da loja",
    href: "/admin",
    icon: LayoutDashboard,
    iconBgColor: "bg-primary",
    keywords: ["inicio", "home", "painel", "dashboard"],
    group: "Páginas",
  },
  {
    id: "pedidos",
    title: "Gerenciamento de Pedidos",
    description: "Gerencie os pedidos da sua loja",
    href: "/admin/pedidos",
    icon: ShoppingCart,
    iconBgColor: "bg-blue-500",
    keywords: ["pedidos", "orders", "vendas", "kanban"],
    group: "Páginas",
  },
  {
    id: "catalogo",
    title: "Catálogo",
    description: "Gerencie seu catálogo de produtos",
    href: "/admin/catalog",
    icon: BookOpen,
    iconBgColor: "bg-emerald-600",
    keywords: ["catalogo", "produtos", "itens", "cardapio", "menu", "complementos"],
    group: "Páginas",
  },
  {
    id: "financeiro",
    title: "Financeiro",
    description: "Gerencie suas mensalidades",
    href: "/admin/financeiro",
    icon: CreditCard,
    iconBgColor: "bg-amber-500",
    keywords: ["financeiro", "pagamentos", "mensalidade", "cobranca", "fatura"],
    group: "Páginas",
  },
  {
    id: "caixa",
    title: "Controle de Caixa",
    description: "Gerencie o fluxo de caixa da sua loja",
    href: "/admin/caixa",
    icon: DollarSign,
    iconBgColor: "bg-green-600",
    keywords: ["caixa", "fluxo", "dinheiro", "sangria", "abertura", "fechamento"],
    group: "Páginas",
  },
  {
    id: "pdv",
    title: "PDV",
    description: "Crie pedidos manualmente",
    href: "/admin/pdv",
    icon: MonitorSmartphone,
    iconBgColor: "bg-indigo-500",
    keywords: ["pdv", "ponto de venda", "balcao", "novo pedido", "manual"],
    group: "Páginas",
  },
  {
    id: "marketing",
    title: "Marketing",
    description: "Estamos trabalhando nisso",
    href: "#marketing",
    icon: Target,
    iconBgColor: "bg-red-500",
    keywords: ["marketing", "campanhas", "promocao"],
    group: "Páginas",
  },
  {
    id: "relatorios",
    title: "Relatórios",
    description: "Acompanhe suas métricas",
    href: "#relatorios",
    icon: BarChart3,
    iconBgColor: "bg-purple-500",
    keywords: ["relatorios", "metricas", "estatisticas", "graficos"],
    group: "Páginas",
  },
  {
    id: "suporte",
    title: "Central de Suporte",
    description: "Área de atendimento e auxílio ao lojista",
    href: "/admin/suporte",
    icon: Headset,
    iconBgColor: "bg-yellow-500",
    keywords: ["suporte", "ajuda", "atendimento", "help"],
    group: "Páginas",
  },

  // Configurações
  {
    id: "settings",
    title: "Configurações",
    description: "Configure sua loja",
    href: "/admin/settings",
    icon: Settings,
    iconBgColor: "bg-gray-600",
    keywords: ["configuracoes", "config", "settings", "preferencias"],
    group: "Configurações",
  },
  {
    id: "settings-general",
    title: "Configurações Gerais",
    description: "Nome, logo, endereço e horários",
    href: "/admin/settings/general",
    icon: Store,
    iconBgColor: "bg-gray-600",
    keywords: ["loja", "nome", "logo", "endereco", "horario", "geral"],
    group: "Configurações",
  },
  {
    id: "settings-users",
    title: "Gerenciamento de Usuários",
    description: "Gerencie usuários e permissões",
    href: "/admin/settings/users",
    icon: Users,
    iconBgColor: "bg-gray-600",
    keywords: ["usuarios", "permissoes", "equipe", "funcionarios", "acesso"],
    group: "Configurações",
  },
  {
    id: "settings-delivery",
    title: "Configurações de Entrega",
    description: "Zonas de entrega e taxas",
    href: "/admin/settings/delivery",
    icon: Truck,
    iconBgColor: "bg-gray-600",
    keywords: ["entrega", "delivery", "taxa", "zona", "frete", "regiao"],
    group: "Configurações",
  },
  {
    id: "settings-payment",
    title: "Configurações de Pagamento",
    description: "Métodos de pagamento aceitos",
    href: "/admin/settings/payment",
    icon: Wallet,
    iconBgColor: "bg-gray-600",
    keywords: ["pagamento", "pix", "cartao", "dinheiro", "metodo"],
    group: "Configurações",
  },
  {
    id: "settings-notifications",
    title: "Notificações WhatsApp",
    description: "Templates de mensagens WhatsApp",
    href: "/admin/settings/notifications",
    icon: Bell,
    iconBgColor: "bg-gray-600",
    keywords: ["notificacoes", "whatsapp", "mensagem", "template", "aviso"],
    group: "Configurações",
  },
]
