import {
  ShoppingCart,
  BookOpen,
  CreditCard,
  Settings,
  Target,
  Ticket,
  BarChart3,
  Headset,
  DollarSign,
  Store,
  Users,
  Truck,
  Wallet,
  Bell,
  MonitorSmartphone,
  LayoutDashboard,
  Contact,
  UtensilsCrossed,
  CalendarDays,
  TrendingUp,
  Clock,
  MapPin,
  UserPlus,
  Timer,
  Shield,
  Eye,
  Palette,
  type LucideIcon,
} from "lucide-react"

export interface AdminSection {
  id: string
  title: string
  description: string
  href: string
  icon: LucideIcon
  iconBgColor: string
  keywords: string[]
  group: string
}

export const adminSections: AdminSection[] = [
  // Páginas principais
  {
    id: "dashboard",
    title: "Dashboard",
    description: "Painel principal da loja",
    href: "/admin",
    icon: LayoutDashboard,
    iconBgColor: "bg-primary",
    keywords: ["inicio", "home", "painel", "dashboard"],
    group: "Páginas",
  },
  {
    id: "pedidos",
    title: "Gerenciamento de Pedidos",
    description: "Gerencie os pedidos da sua loja",
    href: "/admin/pedidos",
    icon: ShoppingCart,
    iconBgColor: "bg-blue-500",
    keywords: ["pedidos", "orders", "vendas", "kanban"],
    group: "Páginas",
  },
  {
    id: "catalogo",
    title: "Catálogo",
    description: "Gerencie seu catálogo de produtos",
    href: "/admin/catalog",
    icon: BookOpen,
    iconBgColor: "bg-emerald-600",
    keywords: ["catalogo", "produtos", "itens", "cardapio", "menu", "complementos"],
    group: "Páginas",
  },
  {
    id: "financeiro",
    title: "Financeiro",
    description: "Gerencie suas mensalidades",
    href: "/admin/financeiro",
    icon: CreditCard,
    iconBgColor: "bg-amber-500",
    keywords: ["financeiro", "pagamentos", "mensalidade", "cobranca", "fatura"],
    group: "Páginas",
  },
  {
    id: "caixa",
    title: "Controle de Caixa",
    description: "Gerencie o fluxo de caixa da sua loja",
    href: "/admin/caixa",
    icon: DollarSign,
    iconBgColor: "bg-green-600",
    keywords: ["caixa", "fluxo", "dinheiro", "sangria", "abertura", "fechamento"],
    group: "Páginas",
  },
  {
    id: "pdv",
    title: "PDV",
    description: "Crie pedidos manualmente",
    href: "/admin/pdv",
    icon: MonitorSmartphone,
    iconBgColor: "bg-indigo-500",
    keywords: ["pdv", "ponto de venda", "balcao", "novo pedido", "manual"],
    group: "Páginas",
  },
  {
    id: "clientes",
    title: "Clientes",
    description: "Gerencie os clientes da sua loja",
    href: "/admin/clientes",
    icon: Contact,
    iconBgColor: "bg-violet-500",
    keywords: ["clientes", "customers", "consumidores", "compradores"],
    group: "Páginas",
  },
  {
    id: "marketing",
    title: "Marketing",
    description: "Ferramentas de marketing e promoções",
    href: "/admin/marketing",
    icon: Target,
    iconBgColor: "bg-red-500",
    keywords: ["marketing", "campanhas", "promocao", "cupom", "desconto"],
    group: "Páginas",
  },
  {
    id: "marketing-coupons",
    title: "Cupons de Desconto",
    description: "Crie e gerencie cupons promocionais",
    href: "/admin/marketing/coupons",
    icon: Ticket,
    iconBgColor: "bg-red-500",
    keywords: ["cupom", "cupons", "desconto", "promocao", "codigo", "voucher"],
    group: "Marketing",
  },
  {
    id: "mesas",
    title: "Mesas",
    description: "Gerencie mesas e comandas do seu estabelecimento",
    href: "/admin/mesas",
    icon: UtensilsCrossed,
    iconBgColor: "bg-orange-500",
    keywords: ["mesas", "mesa", "comanda", "comandas", "table", "tables", "salao"],
    group: "Páginas",
  },
  {
    id: "relatorios",
    title: "Relatórios",
    description: "Acompanhe suas métricas",
    href: "/admin/relatorios",
    icon: BarChart3,
    iconBgColor: "bg-purple-500",
    keywords: ["relatorios", "metricas", "estatisticas", "graficos"],
    group: "Páginas",
  },
  // Relatórios > Faturamento
  {
    id: "relatorios-resumo-semanal",
    title: "Resumo Semanal",
    description: "KPIs da semana: receita, pedidos, ticket médio e comparação",
    href: "/admin/relatorios?cat=faturamento&tab=resumo-semanal",
    icon: BarChart3,
    iconBgColor: "bg-purple-500",
    keywords: ["resumo", "semanal", "semana", "kpi", "dashboard", "relatorio"],
    group: "Relatórios — Faturamento",
  },
  {
    id: "relatorios-vendas-periodo",
    title: "Vendas por Período",
    description: "Relatório de vendas com filtro por data",
    href: "/admin/relatorios?cat=faturamento&tab=vendas-por-periodo",
    icon: CalendarDays,
    iconBgColor: "bg-purple-500",
    keywords: ["vendas", "periodo", "relatorio", "diario", "ticket", "faturamento"],
    group: "Relatórios — Faturamento",
  },
  {
    id: "relatorios-faturamento-mensal",
    title: "Faturamento Mensal",
    description: "Relatório de faturamento mês a mês",
    href: "/admin/relatorios?cat=faturamento&tab=faturamento-mensal",
    icon: TrendingUp,
    iconBgColor: "bg-purple-500",
    keywords: ["faturamento", "mensal", "relatorio", "receita", "revenue"],
    group: "Relatórios — Faturamento",
  },
  {
    id: "relatorios-ticket-medio",
    title: "Ticket Médio",
    description: "Relatório de ticket médio por período",
    href: "/admin/relatorios?cat=faturamento&tab=ticket-medio",
    icon: TrendingUp,
    iconBgColor: "bg-purple-500",
    keywords: ["ticket", "medio", "relatorio", "pedido", "valor"],
    group: "Relatórios — Faturamento",
  },
  {
    id: "relatorios-formas-pagamento",
    title: "Formas de Pagamento",
    description: "Distribuição por forma de pagamento",
    href: "/admin/relatorios?cat=faturamento&tab=formas-de-pagamento",
    icon: Wallet,
    iconBgColor: "bg-purple-500",
    keywords: ["pagamento", "pix", "cartao", "dinheiro", "debito", "credito"],
    group: "Relatórios — Faturamento",
  },
  {
    id: "relatorios-descontos",
    title: "Descontos",
    description: "Relatório de pedidos com desconto e cupons",
    href: "/admin/relatorios?cat=faturamento&tab=descontos",
    icon: Ticket,
    iconBgColor: "bg-purple-500",
    keywords: ["desconto", "cupom", "promocao", "relatorio", "descontos"],
    group: "Relatórios — Faturamento",
  },
  // Relatórios > Vendas
  {
    id: "relatorios-vendas-por-item",
    title: "Vendas por Item",
    description: "Ranking de vendas por item e grupo",
    href: "/admin/relatorios?cat=vendas&tab=vendas-por-item",
    icon: BarChart3,
    iconBgColor: "bg-purple-500",
    keywords: ["vendas", "item", "produto", "ranking", "grupo"],
    group: "Relatórios — Vendas",
  },
  {
    id: "relatorios-vendas-horario",
    title: "Vendas por Horário",
    description: "Volume de vendas por hora do dia",
    href: "/admin/relatorios?cat=vendas&tab=vendas-por-horario",
    icon: Clock,
    iconBgColor: "bg-purple-500",
    keywords: ["vendas", "horario", "hora", "pico", "relatorio"],
    group: "Relatórios — Vendas",
  },
  {
    id: "relatorios-vendas-dia-semana",
    title: "Vendas por Dia da Semana",
    description: "Volume de vendas por dia da semana",
    href: "/admin/relatorios?cat=vendas&tab=vendas-por-dia-semana",
    icon: CalendarDays,
    iconBgColor: "bg-purple-500",
    keywords: ["vendas", "dia", "semana", "segunda", "terca", "relatorio"],
    group: "Relatórios — Vendas",
  },
  {
    id: "relatorios-vendas-bairro",
    title: "Vendas por Bairro",
    description: "Ranking de vendas por bairro de entrega",
    href: "/admin/relatorios?cat=vendas&tab=vendas-por-bairro",
    icon: MapPin,
    iconBgColor: "bg-purple-500",
    keywords: ["vendas", "bairro", "regiao", "entrega", "endereco", "relatorio"],
    group: "Relatórios — Vendas",
  },
  {
    id: "relatorios-vendas-canal",
    title: "Vendas por Canal",
    description: "Distribuição de vendas por Mesa, Balcão e Delivery",
    href: "/admin/relatorios?cat=vendas&tab=vendas-por-canal",
    icon: ShoppingCart,
    iconBgColor: "bg-purple-500",
    keywords: ["vendas", "canal", "mesa", "balcao", "delivery", "entrega", "relatorio"],
    group: "Relatórios — Vendas",
  },
  {
    id: "relatorios-tempo-preparo",
    title: "Tempo de Preparo",
    description: "Tempo médio de preparo dos pedidos",
    href: "/admin/relatorios?cat=vendas&tab=tempo-preparo",
    icon: Timer,
    iconBgColor: "bg-purple-500",
    keywords: ["tempo", "preparo", "preparacao", "media", "minutos", "relatorio"],
    group: "Relatórios — Vendas",
  },
  {
    id: "relatorios-tempo-entrega",
    title: "Tempo de Entrega",
    description: "Tempo médio de entrega dos pedidos",
    href: "/admin/relatorios?cat=vendas&tab=tempo-entrega",
    icon: Truck,
    iconBgColor: "bg-purple-500",
    keywords: ["tempo", "entrega", "delivery", "media", "minutos", "relatorio"],
    group: "Relatórios — Vendas",
  },
  // Relatórios > Clientes
  {
    id: "relatorios-top-clientes",
    title: "Top Clientes",
    description: "Ranking dos melhores clientes",
    href: "/admin/relatorios?cat=clientes&tab=top-clientes",
    icon: Contact,
    iconBgColor: "bg-purple-500",
    keywords: ["clientes", "top", "ranking", "melhor", "compras"],
    group: "Relatórios — Clientes",
  },
  {
    id: "relatorios-aquisicao-clientes",
    title: "Aquisição de Clientes",
    description: "Novos clientes e primeiro pedido",
    href: "/admin/relatorios?cat=clientes&tab=aquisicao-clientes",
    icon: UserPlus,
    iconBgColor: "bg-purple-500",
    keywords: ["aquisicao", "novos", "clientes", "primeiro", "pedido", "relatorio"],
    group: "Relatórios — Clientes",
  },
  // Relatórios > Faturamento (novos)
  {
    id: "relatorios-lucratividade",
    title: "Lucratividade dos Itens",
    description: "Margem de lucro por item vendido",
    href: "/admin/relatorios?cat=faturamento&tab=lucratividade",
    icon: TrendingUp,
    iconBgColor: "bg-purple-500",
    keywords: ["lucratividade", "lucro", "margem", "custo", "profit", "relatorio"],
    group: "Relatórios — Faturamento",
  },
  {
    id: "relatorios-extrato-caixa",
    title: "Extrato de Caixa",
    description: "Extrato detalhado de movimentações do caixa",
    href: "/admin/relatorios?cat=faturamento&tab=extrato-caixa",
    icon: DollarSign,
    iconBgColor: "bg-purple-500",
    keywords: ["extrato", "caixa", "movimentacao", "entrada", "saida", "sangria", "relatorio"],
    group: "Relatórios — Faturamento",
  },
  {
    id: "relatorios-cupons-utilizados",
    title: "Cupons Utilizados",
    description: "Relatório de uso de cupons de desconto",
    href: "/admin/relatorios?cat=faturamento&tab=cupons-utilizados",
    icon: Ticket,
    iconBgColor: "bg-purple-500",
    keywords: ["cupom", "cupons", "desconto", "uso", "utilizados", "relatorio"],
    group: "Relatórios — Faturamento",
  },
  // Relatórios > Vendas (novos)
  {
    id: "relatorios-por-atendente",
    title: "Vendas por Atendente",
    description: "Vendas agrupadas por atendente",
    href: "/admin/relatorios?cat=vendas&tab=por-atendente",
    icon: Users,
    iconBgColor: "bg-purple-500",
    keywords: ["atendente", "vendedor", "usuario", "funcionario", "relatorio"],
    group: "Relatórios — Vendas",
  },
  {
    id: "relatorios-visitantes",
    title: "Visitantes",
    description: "Número de visitantes e taxa de conversão",
    href: "/admin/relatorios?cat=vendas&tab=visitantes",
    icon: Eye,
    iconBgColor: "bg-purple-500",
    keywords: ["visitantes", "visitas", "conversao", "acessos", "relatorio"],
    group: "Relatórios — Vendas",
  },
  {
    id: "relatorios-taxas-entrega",
    title: "Taxas de Entrega",
    description: "Taxas de entrega por motoboy",
    href: "/admin/relatorios?cat=vendas&tab=taxas-entrega",
    icon: Truck,
    iconBgColor: "bg-purple-500",
    keywords: ["taxa", "entrega", "motoboy", "delivery", "frete", "relatorio"],
    group: "Relatórios — Vendas",
  },
  // Relatórios > Auditoria
  {
    id: "relatorios-itens-alterados",
    title: "Itens Alterados",
    description: "Auditoria de alterações e remoções de itens em pedidos",
    href: "/admin/relatorios?cat=auditoria&tab=itens-alterados",
    icon: Shield,
    iconBgColor: "bg-purple-500",
    keywords: ["auditoria", "alteracao", "item", "remocao", "edicao", "relatorio"],
    group: "Relatórios — Auditoria",
  },
  {
    id: "relatorios-pagamento-alterado",
    title: "Pagamento Alterado",
    description: "Auditoria de alterações na forma de pagamento",
    href: "/admin/relatorios?cat=auditoria&tab=pagamento-alterado",
    icon: Shield,
    iconBgColor: "bg-purple-500",
    keywords: ["auditoria", "pagamento", "alteracao", "forma", "relatorio"],
    group: "Relatórios — Auditoria",
  },
  {
    id: "suporte",
    title: "Central de Suporte",
    description: "Área de atendimento e auxílio ao lojista",
    href: "/admin/suporte",
    icon: Headset,
    iconBgColor: "bg-yellow-500",
    keywords: ["suporte", "ajuda", "atendimento", "help"],
    group: "Páginas",
  },

  // Configurações
  {
    id: "settings",
    title: "Configurações",
    description: "Configure sua loja",
    href: "/admin/settings",
    icon: Settings,
    iconBgColor: "bg-gray-600",
    keywords: ["configuracoes", "config", "settings", "preferencias"],
    group: "Configurações",
  },
  {
    id: "settings-general",
    title: "Configurações Gerais",
    description: "Nome, logo, endereço e horários",
    href: "/admin/settings/general",
    icon: Store,
    iconBgColor: "bg-gray-600",
    keywords: ["loja", "nome", "logo", "endereco", "horario", "geral"],
    group: "Configurações",
  },
  {
    id: "settings-appearance",
    title: "Aparência do Cardápio",
    description: "Cores, layout, mensagem de boas-vindas e banner",
    href: "/admin/settings/appearance",
    icon: Palette,
    iconBgColor: "bg-pink-500",
    keywords: ["aparencia", "cores", "layout", "design", "cardapio", "banner", "tema", "visual", "personalizar"],
    group: "Configurações",
  },
  {
    id: "settings-users",
    title: "Gerenciamento de Usuários",
    description: "Gerencie usuários e permissões",
    href: "/admin/settings/users",
    icon: Users,
    iconBgColor: "bg-gray-600",
    keywords: ["usuarios", "permissoes", "equipe", "funcionarios", "acesso"],
    group: "Configurações",
  },
  {
    id: "settings-delivery",
    title: "Configurações de Entrega",
    description: "Zonas de entrega e taxas",
    href: "/admin/settings/delivery",
    icon: Truck,
    iconBgColor: "bg-gray-600",
    keywords: ["entrega", "delivery", "taxa", "zona", "frete", "regiao"],
    group: "Configurações",
  },
  {
    id: "settings-payment",
    title: "Configurações de Pagamento",
    description: "Métodos de pagamento aceitos",
    href: "/admin/settings/payment",
    icon: Wallet,
    iconBgColor: "bg-gray-600",
    keywords: ["pagamento", "pix", "cartao", "dinheiro", "metodo"],
    group: "Configurações",
  },
  {
    id: "settings-notifications",
    title: "Notificações WhatsApp",
    description: "Templates de mensagens WhatsApp",
    href: "/admin/settings/notifications",
    icon: Bell,
    iconBgColor: "bg-gray-600",
    keywords: ["notificacoes", "whatsapp", "mensagem", "template", "aviso"],
    group: "Configurações",
  },
]
