import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
import { Providers } from "./providers";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const antarcticanMono = localFont({
  src: [
    {
      path: "../public/fonts/AntarcticanMono-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/AntarcticanMono-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/AntarcticanMono-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/AntarcticanMono-Book.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-antarctican-mono",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${antarcticanMono.variable} antialiased bg-white`}
      >
        <Toaster position="top-center" />
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}